on: push

name: Publish

jobs:
  pulish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install pypa/build
      run: python -m pip install build

    - name: Build the package
      run: |
        python -m build --sdist --wheel \
        --outdir dist/ .

    - name: Publish
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
